[build]
builder = "NIXPACKS"
watchPatterns = ["/apps/api/**"]

[deploy]
startCommand = "cd apps/api && uvicorn main:app --host 0.0.0.0 --port $PORT & celery -A celery_app worker --concurrency=1 --loglevel=info"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
